
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_Standard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		 reg    [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire RxD;
reg seg7_disp_off_signal;

parameter storage_length = 8;
reg transmit;
wire transmit_debounced;
wire tick;
wire [7:0] receive_data;
//reg [7:0] count_value;
wire receive_done;
wire [7:0] mem_data;
reg [9:0] mem_address;
reg [9:0] written_mem_address;
reg mem_wr;
reg first_val_receive;
reg txdone_flag;
reg [7:0] pixels_tree1[storage_length-1:0];
reg [7:0] Label_tree_1;
wire [7:0] Label;
reg [7:0] serial_transmit_reg;
reg Allpixel_receive_complete;
reg [15:0] state_tree1;
reg ml_inference_completed_tree1;

//=======================================================
//  Structural coding
//=======================================================


Binary_To_7Segment seg1 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_1[3:0] : mem_address[3:0]),  .o_Segment_A(HEX0[0]), .o_Segment_B(HEX0[1]),  .o_Segment_C(HEX0[2]), 
                          .o_Segment_D(HEX0[3]), .o_Segment_E(HEX0[4]), .o_Segment_F(HEX0[5]), .o_Segment_G(HEX0[6]));
								  
Binary_To_7Segment seg2 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_2 : mem_address[7:4]),  .o_Segment_A(HEX1[0]), .o_Segment_B(HEX1[1]),  .o_Segment_C(HEX1[2]), 
                          .o_Segment_D(HEX1[3]), .o_Segment_E(HEX1[4]), .o_Segment_F(HEX1[5]), .o_Segment_G(HEX1[6]));
								  
Binary_To_7Segment seg3 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_3 : mem_address[9:8]),  .o_Segment_A(HEX2[0]), .o_Segment_B(HEX2[1]),  .o_Segment_C(HEX2[2]), 
                          .o_Segment_D(HEX2[3]), .o_Segment_E(HEX2[4]), .o_Segment_F(HEX2[5]), .o_Segment_G(HEX2[6]));
								  
								  
Binary_To_7Segment seg4 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1011 : written_mem_address[3:0]),  .o_Segment_A(HEX3[0]), .o_Segment_B(HEX3[1]),  .o_Segment_C(HEX3[2]), 
                          .o_Segment_D(HEX3[3]), .o_Segment_E(HEX3[4]), .o_Segment_F(HEX3[5]), .o_Segment_G(HEX3[6]));
								  
Binary_To_7Segment seg5 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1010 : written_mem_address[7:4]),  .o_Segment_A(HEX4[0]), .o_Segment_B(HEX4[1]),  .o_Segment_C(HEX4[2]), 
                          .o_Segment_D(HEX4[3]), .o_Segment_E(HEX4[4]), .o_Segment_F(HEX4[5]), .o_Segment_G(HEX4[6]));
								  
Binary_To_7Segment seg6 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b0001 : written_mem_address[9:8]),  .o_Segment_A(HEX5[0]), .o_Segment_B(HEX5[1]),  .o_Segment_C(HEX5[2]), 
                          .o_Segment_D(HEX5[3]), .o_Segment_E(HEX5[4]), .o_Segment_F(HEX5[5]), .o_Segment_G(HEX5[6]));

					  
								  
assign RxD = GPIO[0];  //UART receiver pin for FPGA
// GPIO[1];  //UART transmitter Pin for FPGA


uart_rx R3 (.i_Clock(CLOCK_50), .i_Rx_Serial(RxD), .o_Rx_DV(receive_done), .o_Rx_Byte(receive_data) );

always @ (posedge receive_done)
begin
      if (SW[0] == 1)    begin LEDR[1] <= 0; end
      else begin LEDR[1] <= ~LEDR[1]; end
end

always @ (posedge CLOCK_50)
begin
    if (receive_done == 1)
        begin
        mem_address <= mem_address+1;   written_mem_address <= mem_address; 
        pixels_tree1[mem_address] <= receive_data;
        if (mem_address >= storage_length-1)
        begin Allpixel_receive_complete <=1; end
        else
        begin Allpixel_receive_complete <=0; end
        end
            
     if (SW[0] == 1)
         begin
            mem_address <= 0;
				seg7_disp_off_signal <=0;
         end
     
     if (tick == 1)
         begin
           if (txdone_flag == 0 )
               begin
                    txdone_flag <= 1;
               end
           else 
               begin
                    mem_address <= mem_address+1;
                    txdone_flag <= 0;
               end              
         end
     
     if (mem_address < written_mem_address && SW[1]== 1)
     begin
        transmit <= 1;    
        serial_transmit_reg <= pixels_tree1[mem_address];    
     end
     else if (mem_address == written_mem_address && SW[1]== 1)
     begin 
        transmit <= 1;   
        serial_transmit_reg <= Label;    
     end
     else
     begin
        transmit <=0; 
     end 
	  
	  if (SW[2] == 1)
         begin
				seg7_disp_off_signal <= 1;
         end
end

uart_tx T1 (.i_Clock(CLOCK_50), .i_Tx_DV(transmit), .i_Tx_Byte(serial_transmit_reg), .o_Tx_Active(), .o_Tx_Serial(GPIO[1]), .o_Tx_Done(tick) );

assign Label = Label_tree_1;

always @ (posedge CLOCK_50)
    begin
    if (SW[0] == 1)
         begin
            state_tree1 <= 0;
         end
         
    if (Allpixel_receive_complete==1)
        begin
 case (state_tree1)        


16'd0:if (pixels_tree1[2] <= 361) begin state_tree1<=1; end  else begin state_tree1<=34; end 
 
16'd1:if (pixels_tree1[7] <= 10) begin state_tree1<=2; end  else begin state_tree1<=31; end 
 
16'd2:if (pixels_tree1[3] <= 394) begin state_tree1<=3; end  else begin state_tree1<=14; end 
 
16'd3:if (pixels_tree1[7] <= 4) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=5; end 

16'd5:if (pixels_tree1[1] <= 812) begin state_tree1<=6; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd6:if (pixels_tree1[6] <= 49) begin state_tree1<=7; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd7:if (pixels_tree1[6] <= 48) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=9; end 

16'd9:if (pixels_tree1[1] <= 796) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd14:if (pixels_tree1[4] <= 2) begin state_tree1<=15; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd15:if (pixels_tree1[5] <= 381) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=17; end 

16'd17:if (pixels_tree1[5] <= 397) begin state_tree1<=18; end  else begin state_tree1<=23; end 
 
16'd18:if (pixels_tree1[7] <= 4) begin state_tree1<=19; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd19:if (pixels_tree1[6] <= 430) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd23:if (pixels_tree1[3] <= 566) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=25; end 

16'd25:if (pixels_tree1[7] <= 5) begin state_tree1<=26; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd26:if (pixels_tree1[1] <= 854) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd31:if (pixels_tree1[3] <= 99) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd34:if (pixels_tree1[1] <= 572) begin state_tree1<=35; end  else begin state_tree1<=260; end 
 
16'd35:if (pixels_tree1[5] <= 560) begin state_tree1<=36; end  else begin state_tree1<=217; end 
 
16'd36:if (pixels_tree1[7] <= 9) begin state_tree1<=37; end  else begin state_tree1<=134; end 
 
16'd37:if (pixels_tree1[5] <= 462) begin state_tree1<=38; end  else begin state_tree1<=97; end 
 
16'd38:if (pixels_tree1[4] <= 0) begin state_tree1<=39; end  else begin state_tree1<=66; end 
 
16'd39:if (pixels_tree1[2] <= 634) begin state_tree1<=40; end  else begin state_tree1<=55; end 
 
16'd40:if (pixels_tree1[6] <= 632) begin state_tree1<=41; end  else begin state_tree1<=48; end 
 
16'd41:if (pixels_tree1[5] <= 170) begin state_tree1<=42; end  else begin state_tree1<=45; end 
 
16'd42:if (pixels_tree1[6] <= 46) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd45:if (pixels_tree1[3] <= 178) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd48:if (pixels_tree1[2] <= 579) begin state_tree1<=49; end  else begin state_tree1<=52; end 
 
16'd49:if (pixels_tree1[3] <= 373) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd52:if (pixels_tree1[5] <= 154) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd55:if (pixels_tree1[0] <= 0) begin state_tree1<=56; end  else begin state_tree1<=59; end 
 
16'd56:if (pixels_tree1[6] <= 911) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd59:if (pixels_tree1[1] <= 428) begin state_tree1<=60; end  else begin state_tree1<=63; end 
 
16'd60:if (pixels_tree1[5] <= 161) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd63:if (pixels_tree1[3] <= 415) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd66:if (pixels_tree1[5] <= 381) begin state_tree1<=67; end  else begin state_tree1<=82; end 
 
16'd67:if (pixels_tree1[1] <= 439) begin state_tree1<=68; end  else begin state_tree1<=75; end 
 
16'd68:if (pixels_tree1[3] <= 229) begin state_tree1<=69; end  else begin state_tree1<=72; end 
 
16'd69:if (pixels_tree1[1] <= 330) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd72:if (pixels_tree1[6] <= 24) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd75:if (pixels_tree1[4] <= 1) begin state_tree1<=76; end  else begin state_tree1<=79; end 
 
16'd76:if (pixels_tree1[2] <= 590) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd79:if (pixels_tree1[5] <= 56) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd82:if (pixels_tree1[1] <= 449) begin state_tree1<=83; end  else begin state_tree1<=90; end 
 
16'd83:if (pixels_tree1[2] <= 611) begin state_tree1<=84; end  else begin state_tree1<=87; end 
 
16'd84:if (pixels_tree1[1] <= 364) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd87:if (pixels_tree1[1] <= 327) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd90:if (pixels_tree1[1] <= 540) begin state_tree1<=91; end  else begin state_tree1<=94; end 
 
16'd91:if (pixels_tree1[4] <= 1) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd94:if (pixels_tree1[5] <= 413) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd97:if (pixels_tree1[0] <= 0) begin state_tree1<=98; end  else begin state_tree1<=121; end 
 
16'd98:if (pixels_tree1[3] <= 243) begin state_tree1<=99; end  else begin state_tree1<=108; end 
 
16'd99:if (pixels_tree1[4] <= 0) begin state_tree1<=100; end  else begin state_tree1<=103; end 
 
16'd100:if (pixels_tree1[2] <= 593) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd103:if (pixels_tree1[4] <= 2) begin state_tree1<=104; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd104:if (pixels_tree1[2] <= 636) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd108:if (pixels_tree1[2] <= 588) begin state_tree1<=109; end  else begin state_tree1<=114; end 
 
16'd109:if (pixels_tree1[4] <= 1) begin state_tree1<=110; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd110:if (pixels_tree1[6] <= 556) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd114:if (pixels_tree1[6] <= 857) begin state_tree1<=115; end  else begin state_tree1<=118; end 
 
16'd115:if (pixels_tree1[4] <= 1) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd118:if (pixels_tree1[4] <= 2) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd121:if (pixels_tree1[1] <= 553) begin state_tree1<=122; end  else begin state_tree1<=131; end 
 
16'd122:if (pixels_tree1[3] <= 394) begin state_tree1<=123; end  else begin state_tree1<=128; end 
 
16'd123:if (pixels_tree1[4] <= 1) begin state_tree1<=124; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd124:if (pixels_tree1[1] <= 385) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd128:if (pixels_tree1[4] <= 1) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd131:if (pixels_tree1[4] <= 2) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd134:if (pixels_tree1[1] <= 433) begin state_tree1<=135; end  else begin state_tree1<=176; end 
 
16'd135:if (pixels_tree1[4] <= 1) begin state_tree1<=136; end  else begin state_tree1<=161; end 
 
16'd136:if (pixels_tree1[0] <= 0) begin state_tree1<=137; end  else begin state_tree1<=148; end 
 
16'd137:if (pixels_tree1[7] <= 10) begin state_tree1<=138; end  else begin state_tree1<=143; end 
 
16'd138:if (pixels_tree1[3] <= 363) begin state_tree1<=139; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd139:if (pixels_tree1[3] <= 281) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd143:if (pixels_tree1[2] <= 538) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=145; end 

16'd145:if (pixels_tree1[2] <= 634) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd148:if (pixels_tree1[4] <= 0) begin state_tree1<=149; end  else begin state_tree1<=156; end 
 
16'd149:if (pixels_tree1[2] <= 552) begin state_tree1<=150; end  else begin state_tree1<=153; end 
 
16'd150:if (pixels_tree1[5] <= 316) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd153:if (pixels_tree1[5] <= 145) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd156:if (pixels_tree1[3] <= 442) begin state_tree1<=157; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd157:if (pixels_tree1[5] <= 486) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd161:if (pixels_tree1[2] <= 615) begin state_tree1<=162; end  else begin state_tree1<=167; end 
 
16'd162:if (pixels_tree1[5] <= 202) begin state_tree1<=163; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd163:if (pixels_tree1[0] <= 0) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd167:if (pixels_tree1[6] <= 180) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=169; end 

16'd169:if (pixels_tree1[1] <= 385) begin state_tree1<=170; end  else begin state_tree1<=173; end 
 
16'd170:if (pixels_tree1[3] <= 209) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd173:if (pixels_tree1[3] <= 215) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd176:if (pixels_tree1[5] <= 446) begin state_tree1<=177; end  else begin state_tree1<=204; end 
 
16'd177:if (pixels_tree1[4] <= 0) begin state_tree1<=178; end  else begin state_tree1<=191; end 
 
16'd178:if (pixels_tree1[5] <= 121) begin state_tree1<=179; end  else begin state_tree1<=184; end 
 
16'd179:if (pixels_tree1[7] <= 10) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=181; end 

16'd181:if (pixels_tree1[5] <= 88) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd184:if (pixels_tree1[3] <= 408) begin state_tree1<=185; end  else begin state_tree1<=188; end 
 
16'd185:if (pixels_tree1[6] <= 163) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd188:if (pixels_tree1[2] <= 574) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd191:if (pixels_tree1[4] <= 1) begin state_tree1<=192; end  else begin state_tree1<=197; end 
 
16'd192:if (pixels_tree1[1] <= 516) begin state_tree1<=193; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd193:if (pixels_tree1[2] <= 561) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd197:if (pixels_tree1[3] <= 243) begin state_tree1<=198; end  else begin state_tree1<=201; end 
 
16'd198:if (pixels_tree1[0] <= 0) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd201:if (pixels_tree1[5] <= 430) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd204:if (pixels_tree1[4] <= 1) begin state_tree1<=205; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd205:if (pixels_tree1[3] <= 298) begin state_tree1<=206; end  else begin state_tree1<=209; end 
 
16'd206:if (pixels_tree1[4] <= 0) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd209:if (pixels_tree1[5] <= 495) begin state_tree1<=210; end  else begin state_tree1<=213; end 
 
16'd210:if (pixels_tree1[6] <= 337) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd213:if (pixels_tree1[4] <= 0) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd217:if (pixels_tree1[5] <= 592) begin state_tree1<=218; end  else begin state_tree1<=227; end 
 
16'd218:if (pixels_tree1[6] <= 145) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=220; end 

16'd220:if (pixels_tree1[7] <= 3) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=222; end 

16'd222:if (pixels_tree1[1] <= 441) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=224; end 

16'd224:if (pixels_tree1[3] <= 401) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd227:if (pixels_tree1[1] <= 532) begin state_tree1<=228; end  else begin state_tree1<=251; end 
 
16'd228:if (pixels_tree1[2] <= 717) begin state_tree1<=229; end  else begin state_tree1<=246; end 
 
16'd229:if (pixels_tree1[3] <= 102) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=231; end 

16'd231:if (pixels_tree1[5] <= 625) begin state_tree1<=232; end  else begin state_tree1<=239; end 
 
16'd232:if (pixels_tree1[2] <= 672) begin state_tree1<=233; end  else begin state_tree1<=236; end 
 
16'd233:if (pixels_tree1[3] <= 301) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd236:if (pixels_tree1[7] <= 0) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd239:if (pixels_tree1[6] <= 8) begin state_tree1<=240; end  else begin state_tree1<=243; end 
 
16'd240:if (pixels_tree1[5] <= 673) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd243:if (pixels_tree1[2] <= 588) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd246:if (pixels_tree1[7] <= 9) begin state_tree1<=247; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd247:if (pixels_tree1[5] <= 641) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd251:if (pixels_tree1[1] <= 540) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=253; end 

16'd253:if (pixels_tree1[6] <= 923) begin state_tree1<=254; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd254:if (pixels_tree1[2] <= 574) begin state_tree1<=255; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd255:if (pixels_tree1[3] <= 322) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd260:if (pixels_tree1[4] <= 1) begin state_tree1<=261; end  else begin state_tree1<=386; end 
 
16'd261:if (pixels_tree1[5] <= 413) begin state_tree1<=262; end  else begin state_tree1<=349; end 
 
16'd262:if (pixels_tree1[1] <= 625) begin state_tree1<=263; end  else begin state_tree1<=310; end 
 
16'd263:if (pixels_tree1[3] <= 332) begin state_tree1<=264; end  else begin state_tree1<=285; end 
 
16'd264:if (pixels_tree1[3] <= 311) begin state_tree1<=265; end  else begin state_tree1<=278; end 
 
16'd265:if (pixels_tree1[5] <= 105) begin state_tree1<=266; end  else begin state_tree1<=271; end 
 
16'd266:if (pixels_tree1[2] <= 565) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=268; end 

16'd268:if (pixels_tree1[1] <= 593) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd271:if (pixels_tree1[5] <= 365) begin state_tree1<=272; end  else begin state_tree1<=275; end 
 
16'd272:if (pixels_tree1[7] <= 10) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd275:if (pixels_tree1[4] <= 0) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd278:if (pixels_tree1[0] <= 0) begin state_tree1<=279; end  else begin state_tree1<=282; end 
 
16'd279:if (pixels_tree1[4] <= 0) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd282:if (pixels_tree1[1] <= 604) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd285:if (pixels_tree1[5] <= 121) begin state_tree1<=286; end  else begin state_tree1<=297; end 
 
16'd286:if (pixels_tree1[6] <= 435) begin state_tree1<=287; end  else begin state_tree1<=294; end 
 
16'd287:if (pixels_tree1[0] <= 0) begin state_tree1<=288; end  else begin state_tree1<=291; end 
 
16'd288:if (pixels_tree1[2] <= 565) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd291:if (pixels_tree1[2] <= 561) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd294:if (pixels_tree1[3] <= 363) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd297:if (pixels_tree1[1] <= 599) begin state_tree1<=298; end  else begin state_tree1<=305; end 
 
16'd298:if (pixels_tree1[5] <= 300) begin state_tree1<=299; end  else begin state_tree1<=302; end 
 
16'd299:if (pixels_tree1[6] <= 1021) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd302:if (pixels_tree1[2] <= 570) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd305:if (pixels_tree1[4] <= 0) begin state_tree1<=306; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd306:if (pixels_tree1[7] <= 6) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd310:if (pixels_tree1[5] <= 137) begin state_tree1<=311; end  else begin state_tree1<=326; end 
 
16'd311:if (pixels_tree1[0] <= 0) begin state_tree1<=312; end  else begin state_tree1<=317; end 
 
16'd312:if (pixels_tree1[3] <= 439) begin state_tree1<=313; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd313:if (pixels_tree1[2] <= 600) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd317:if (pixels_tree1[6] <= 1010) begin state_tree1<=318; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd318:if (pixels_tree1[5] <= 105) begin state_tree1<=319; end  else begin state_tree1<=322; end 
 
16'd319:if (pixels_tree1[3] <= 332) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd322:if (pixels_tree1[1] <= 639) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd326:if (pixels_tree1[3] <= 442) begin state_tree1<=327; end  else begin state_tree1<=338; end 
 
16'd327:if (pixels_tree1[5] <= 349) begin state_tree1<=328; end  else begin state_tree1<=333; end 
 
16'd328:if (pixels_tree1[4] <= 0) begin state_tree1<=329; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd329:if (pixels_tree1[2] <= 370) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd333:if (pixels_tree1[4] <= 0) begin state_tree1<=334; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd334:if (pixels_tree1[3] <= 435) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd338:if (pixels_tree1[1] <= 718) begin state_tree1<=339; end  else begin state_tree1<=344; end 
 
16'd339:if (pixels_tree1[5] <= 283) begin state_tree1<=340; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd340:if (pixels_tree1[6] <= 762) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd344:if (pixels_tree1[2] <= 447) begin state_tree1<=345; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd345:if (pixels_tree1[6] <= 599) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd349:if (pixels_tree1[2] <= 565) begin state_tree1<=350; end  else begin state_tree1<=379; end 
 
16'd350:if (pixels_tree1[4] <= 0) begin state_tree1<=351; end  else begin state_tree1<=360; end 
 
16'd351:if (pixels_tree1[7] <= 2) begin state_tree1<=352; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd352:if (pixels_tree1[3] <= 555) begin state_tree1<=353; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd353:if (pixels_tree1[2] <= 452) begin state_tree1<=354; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd354:if (pixels_tree1[2] <= 443) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd360:if (pixels_tree1[1] <= 604) begin state_tree1<=361; end  else begin state_tree1<=370; end 
 
16'd361:if (pixels_tree1[6] <= 190) begin state_tree1<=362; end  else begin state_tree1<=367; end 
 
16'd362:if (pixels_tree1[7] <= 4) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=364; end 

16'd364:if (pixels_tree1[1] <= 599) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd367:if (pixels_tree1[5] <= 511) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd370:if (pixels_tree1[3] <= 318) begin state_tree1<=371; end  else begin state_tree1<=376; end 
 
16'd371:if (pixels_tree1[3] <= 298) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=373; end 

16'd373:if (pixels_tree1[0] <= 0) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd376:if (pixels_tree1[5] <= 592) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd379:if (pixels_tree1[4] <= 0) begin state_tree1<=380; end  else begin state_tree1<=383; end 
 
16'd380:if (pixels_tree1[2] <= 593) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd383:if (pixels_tree1[5] <= 641) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd386:if (pixels_tree1[5] <= 72) begin state_tree1<=387; end  else begin state_tree1<=392; end 
 
16'd387:if (pixels_tree1[0] <= 0) begin state_tree1<=388; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd388:if (pixels_tree1[2] <= 488) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd392:if (pixels_tree1[1] <= 716) begin state_tree1<=393; end  else begin state_tree1<=416; end 
 
16'd393:if (pixels_tree1[2] <= 588) begin state_tree1<=394; end  else begin state_tree1<=411; end 
 
16'd394:if (pixels_tree1[1] <= 631) begin state_tree1<=395; end  else begin state_tree1<=404; end 
 
16'd395:if (pixels_tree1[4] <= 2) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=397; end 

16'd397:if (pixels_tree1[2] <= 543) begin state_tree1<=398; end  else begin state_tree1<=401; end 
 
16'd398:if (pixels_tree1[5] <= 462) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd401:if (pixels_tree1[7] <= 3) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd404:if (pixels_tree1[3] <= 641) begin state_tree1<=405; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd405:if (pixels_tree1[1] <= 689) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=407; end 

16'd407:if (pixels_tree1[1] <= 694) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd411:if (pixels_tree1[1] <= 599) begin state_tree1<=412; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd412:if (pixels_tree1[6] <= 139) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd416:if (pixels_tree1[2] <= 365) begin state_tree1<=417; end  else begin state_tree1<=422; end 
 
16'd417:if (pixels_tree1[6] <= 997) begin state_tree1<=418; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd418:if (pixels_tree1[1] <= 785) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd422:if (pixels_tree1[1] <= 737) begin state_tree1<=423; end  else begin state_tree1<=432; end 
 
16'd423:if (pixels_tree1[0] <= 0) begin state_tree1<=424; end  else begin state_tree1<=427; end 
 
16'd424:if (pixels_tree1[2] <= 404) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd427:if (pixels_tree1[4] <= 2) begin state_tree1<=428; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd428:if (pixels_tree1[7] <= 8) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd432:if (pixels_tree1[2] <= 408) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=434; end 

16'd434:if (pixels_tree1[1] <= 825) begin state_tree1<=435; end  else begin state_tree1<=438; end 
 
16'd435:if (pixels_tree1[7] <= 2) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd438:if (pixels_tree1[1] <= 868) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

		 endcase
     
        end
    end




endmodule

module Binary_To_7Segment 
  (
   input       i_Clk,
	input [3:0] i_Binary_Num,
   output      o_Segment_A,
   output      o_Segment_B,
   output      o_Segment_C,
   output      o_Segment_D,
   output      o_Segment_E,
   output      o_Segment_F,
   output      o_Segment_G
   );
 
  reg [6:0]    r_Hex_Encoding = 7'h00;
   
  // Purpose: Creates a case statement for all possible input binary numbers.
  // Drives r_Hex_Encoding appropriately for each input combination.
  // Encoding at https://www.fpga4student.com/2017/09/seven-segment-led-display-controller-basys3-fpga.html
  always @(posedge i_Clk)
    begin
      case (i_Binary_Num)
        4'b0000 : r_Hex_Encoding <= 7'b0000001;
        4'b0001 : r_Hex_Encoding <= 7'b1001111;
        4'b0010 : r_Hex_Encoding <= 7'b0010010;
        4'b0011 : r_Hex_Encoding <= 7'b0000110;
        4'b0100 : r_Hex_Encoding <= 7'b1001100;         
        4'b0101 : r_Hex_Encoding <= 7'b0100100;
        4'b0110 : r_Hex_Encoding <= 7'b0100000;
        4'b0111 : r_Hex_Encoding <= 7'b0001111;
        4'b1000 : r_Hex_Encoding <= 7'b0000000;
        4'b1001 : r_Hex_Encoding <= 7'b0000100; 
		  4'b1010 : r_Hex_Encoding <= 7'b0001000; //a
		  4'b1011 : r_Hex_Encoding <= 7'b1100000; //b
		  4'b1100 : r_Hex_Encoding <= 7'b0110001;  //c
		  4'b1101 : r_Hex_Encoding <= 7'b1000010;  //d
		  4'b1110 : r_Hex_Encoding <= 7'b0110000;  //e
		  4'b1111 : r_Hex_Encoding <= 7'b0111000;  //f
        default: r_Hex_Encoding = 7'b1111111;
      endcase
    end // always @ (posedge i_Clk)
 
  // r_Hex_Encoding[7] is unused
  assign o_Segment_A = r_Hex_Encoding[6];
  assign o_Segment_B = r_Hex_Encoding[5];
  assign o_Segment_C = r_Hex_Encoding[4];
  assign o_Segment_D = r_Hex_Encoding[3];
  assign o_Segment_E = r_Hex_Encoding[2];
  assign o_Segment_F = r_Hex_Encoding[1];
  assign o_Segment_G = r_Hex_Encoding[0];
 
endmodule // Binary_To_7Segment



//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Receiver.  This receiver is able to
// receive 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When receive is complete o_rx_dv will be
// driven high for one clock cycle.
// https://www.nandland.com/vhdl/modules/module-uart-serial-port-rs232.html
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_rx   #(parameter CLKS_PER_BIT = 53)
  (
   input        i_Clock,
   input        i_Rx_Serial,
   output       o_Rx_DV,
   output [7:0] o_Rx_Byte
   );
    
  parameter s_IDLE         = 3'b000;
  parameter s_RX_START_BIT = 3'b001;
  parameter s_RX_DATA_BITS = 3'b010;
  parameter s_RX_STOP_BIT  = 3'b011; 
  parameter s_CLEANUP      = 3'b100;
   
  reg           r_Rx_Data_R = 1'b1;
  reg           r_Rx_Data   = 1'b1;
   
  reg [7:0]     r_Clock_Count = 0;
  reg [2:0]     r_Bit_Index   = 0; //8 bits total
  reg [7:0]     r_Rx_Byte     = 0;
  reg           r_Rx_DV       = 0;
  reg [2:0]     r_SM_Main     = 0;
   
  // Purpose: Double-register the incoming data.
  // This allows it to be used in the UART RX Clock Domain.
  // (It removes problems caused by metastability)
  always @(posedge i_Clock)
    begin
      r_Rx_Data_R <= i_Rx_Serial;
      r_Rx_Data   <= r_Rx_Data_R;
    end
   
   
  // Purpose: Control RX state machine
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            r_Rx_DV       <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (r_Rx_Data == 1'b0)          // Start bit detected
              r_SM_Main <= s_RX_START_BIT;
            else
              r_SM_Main <= s_IDLE;
          end
         
        // Check middle of start bit to make sure it's still low
        s_RX_START_BIT :
          begin
            if (r_Clock_Count == (CLKS_PER_BIT-1)/2)
              begin
                if (r_Rx_Data == 1'b0)
                  begin
                    r_Clock_Count <= 0;  // reset counter, found the middle
                    r_SM_Main     <= s_RX_DATA_BITS;
                  end
                else
                  r_SM_Main <= s_IDLE;
              end
            else
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_START_BIT;
              end
          end // case: s_RX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles to sample serial data
        s_RX_DATA_BITS :
          begin
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count          <= 0;
                r_Rx_Byte[r_Bit_Index] <= r_Rx_Data;
                 
                // Check if we have received all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_RX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_RX_STOP_BIT;
                  end
              end
          end // case: s_RX_DATA_BITS
     
     
        // Receive Stop bit.  Stop bit = 1
        s_RX_STOP_BIT :
          begin
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_STOP_BIT;
              end
            else
              begin
                r_Rx_DV       <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
              end
          end // case: s_RX_STOP_BIT
     
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_SM_Main <= s_IDLE;
            r_Rx_DV   <= 1'b0;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end   
   
  assign o_Rx_DV   = r_Rx_DV;
  assign o_Rx_Byte = r_Rx_Byte;
   
endmodule // uart_rx


//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Transmitter.  This transmitter is able
// to transmit 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When transmit is complete o_Tx_done will be
// driven high for one clock cycle.
//
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_tx 
  #(parameter CLKS_PER_BIT = 53)
  (
   input       i_Clock,
   input       i_Tx_DV,
   input [7:0] i_Tx_Byte, 
   output      o_Tx_Active,
   output reg  o_Tx_Serial,
   output      o_Tx_Done
   );
  
  parameter s_IDLE         = 3'b000;
  parameter s_TX_START_BIT = 3'b001;
  parameter s_TX_DATA_BITS = 3'b010;
  parameter s_TX_STOP_BIT  = 3'b011;
  parameter s_CLEANUP      = 3'b100;
   
  reg [2:0]    r_SM_Main     = 0;
  reg [7:0]    r_Clock_Count = 0;
  reg [2:0]    r_Bit_Index   = 0;
  reg [7:0]    r_Tx_Data     = 0;
  reg          r_Tx_Done     = 0;
  reg          r_Tx_Active   = 0;
     
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            o_Tx_Serial   <= 1'b1;         // Drive Line High for Idle
            r_Tx_Done     <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (i_Tx_DV == 1'b1)
              begin
                r_Tx_Active <= 1'b1;
                r_Tx_Data   <= i_Tx_Byte;
                r_SM_Main   <= s_TX_START_BIT;
              end
            else
              r_SM_Main <= s_IDLE;
          end // case: s_IDLE
         
         
        // Send out Start Bit. Start bit = 0
        s_TX_START_BIT :
          begin
            o_Tx_Serial <= 1'b0;
             
            // Wait CLKS_PER_BIT-1 clock cycles for start bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_START_BIT;
              end
            else
              begin
                r_Clock_Count <= 0;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
          end // case: s_TX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles for data bits to finish         
        s_TX_DATA_BITS :
          begin
            o_Tx_Serial <= r_Tx_Data[r_Bit_Index];
             
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count <= 0;
                 
                // Check if we have sent out all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_TX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_TX_STOP_BIT;
                  end
              end
          end // case: s_TX_DATA_BITS
         
         
        // Send out Stop bit.  Stop bit = 1
        s_TX_STOP_BIT :
          begin
            o_Tx_Serial <= 1'b1;
             
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_STOP_BIT;
              end
            else
              begin
                r_Tx_Done     <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
                r_Tx_Active   <= 1'b0;
              end
          end // case: s_Tx_STOP_BIT
         
         
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_Tx_Done <= 1'b1;
            r_SM_Main <= s_IDLE;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end
 
  assign o_Tx_Active = r_Tx_Active;
  assign o_Tx_Done   = r_Tx_Done;
   
endmodule

