
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE10_Standard(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// LED //////////
	output		 reg    [9:0]		LEDR,

	//////////// Seg7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// GPIO, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================
wire RxD;
reg seg7_disp_off_signal;

parameter storage_length = 784;
reg transmit;
wire transmit_debounced;
wire tick;
wire [7:0] receive_data;
//reg [7:0] count_value;
wire receive_done;
wire [7:0] mem_data;
reg [9:0] mem_address;
reg [9:0] written_mem_address;
reg mem_wr;
reg first_val_receive;
reg txdone_flag;
reg [7:0] pixels_tree1[storage_length-1:0];
reg [7:0] Label_tree_1;
wire [7:0] Label;
reg [7:0] serial_transmit_reg;
reg Allpixel_receive_complete;
reg [15:0] state_tree1;
reg ml_inference_completed_tree1;

//=======================================================
//  Structural coding
//=======================================================


Binary_To_7Segment seg1 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_1[3:0] : mem_address[3:0]),  .o_Segment_A(HEX0[0]), .o_Segment_B(HEX0[1]),  .o_Segment_C(HEX0[2]), 
                          .o_Segment_D(HEX0[3]), .o_Segment_E(HEX0[4]), .o_Segment_F(HEX0[5]), .o_Segment_G(HEX0[6]));
								  
Binary_To_7Segment seg2 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_2 : mem_address[7:4]),  .o_Segment_A(HEX1[0]), .o_Segment_B(HEX1[1]),  .o_Segment_C(HEX1[2]), 
                          .o_Segment_D(HEX1[3]), .o_Segment_E(HEX1[4]), .o_Segment_F(HEX1[5]), .o_Segment_G(HEX1[6]));
								  
Binary_To_7Segment seg3 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? Label_tree_3 : mem_address[9:8]),  .o_Segment_A(HEX2[0]), .o_Segment_B(HEX2[1]),  .o_Segment_C(HEX2[2]), 
                          .o_Segment_D(HEX2[3]), .o_Segment_E(HEX2[4]), .o_Segment_F(HEX2[5]), .o_Segment_G(HEX2[6]));
								  
								  
Binary_To_7Segment seg4 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1011 : written_mem_address[3:0]),  .o_Segment_A(HEX3[0]), .o_Segment_B(HEX3[1]),  .o_Segment_C(HEX3[2]), 
                          .o_Segment_D(HEX3[3]), .o_Segment_E(HEX3[4]), .o_Segment_F(HEX3[5]), .o_Segment_G(HEX3[6]));
								  
Binary_To_7Segment seg5 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b1010 : written_mem_address[7:4]),  .o_Segment_A(HEX4[0]), .o_Segment_B(HEX4[1]),  .o_Segment_C(HEX4[2]), 
                          .o_Segment_D(HEX4[3]), .o_Segment_E(HEX4[4]), .o_Segment_F(HEX4[5]), .o_Segment_G(HEX4[6]));
								  
Binary_To_7Segment seg6 (.i_Clk(CLOCK_50), .i_Binary_Num(seg7_disp_off_signal? 4'b0001 : written_mem_address[9:8]),  .o_Segment_A(HEX5[0]), .o_Segment_B(HEX5[1]),  .o_Segment_C(HEX5[2]), 
                          .o_Segment_D(HEX5[3]), .o_Segment_E(HEX5[4]), .o_Segment_F(HEX5[5]), .o_Segment_G(HEX5[6]));

					  
								  
assign RxD = GPIO[0];  //UART receiver pin for FPGA
// GPIO[1];  //UART transmitter Pin for FPGA


uart_rx R3 (.i_Clock(CLOCK_50), .i_Rx_Serial(RxD), .o_Rx_DV(receive_done), .o_Rx_Byte(receive_data) );

always @ (posedge receive_done)
begin
      if (SW[0] == 1)    begin LEDR[1] <= 0; end
      else begin LEDR[1] <= ~LEDR[1]; end
end

always @ (posedge CLOCK_50)
begin
    if (receive_done == 1)
        begin
        mem_address <= mem_address+1;   written_mem_address <= mem_address; 
        pixels_tree1[mem_address] <= receive_data;
        if (mem_address >= storage_length-1)
        begin Allpixel_receive_complete <=1; end
        else
        begin Allpixel_receive_complete <=0; end
        end
            
     if (SW[0] == 1)
         begin
            mem_address <= 0;
				seg7_disp_off_signal <=0;
         end
     
     if (tick == 1)
         begin
           if (txdone_flag == 0 )
               begin
                    txdone_flag <= 1;
               end
           else 
               begin
                    mem_address <= mem_address+1;
                    txdone_flag <= 0;
               end              
         end
     
     if (mem_address < written_mem_address && SW[1]== 1)
     begin
        transmit <= 1;    
        serial_transmit_reg <= pixels_tree1[mem_address];    
     end
     else if (mem_address == written_mem_address && SW[1]== 1)
     begin 
        transmit <= 1;   
        serial_transmit_reg <= Label;    
     end
     else
     begin
        transmit <=0; 
     end 
	  
	  if (SW[2] == 1)
         begin
				seg7_disp_off_signal <= 1;
         end
end

uart_tx T1 (.i_Clock(CLOCK_50), .i_Tx_DV(transmit), .i_Tx_Byte(serial_transmit_reg), .o_Tx_Active(), .o_Tx_Serial(GPIO[1]), .o_Tx_Done(tick) );

assign Label = Label_tree_1;

always @ (posedge CLOCK_50)
    begin
    if (SW[0] == 1)
         begin
            state_tree1 <= 0;
         end
         
    if (Allpixel_receive_complete==1)
        begin
 case (state_tree1)        

16'd0:if (pixels_tree1[407] <= 0) begin state_tree1<=1; end  else begin state_tree1<=238; end 
 
16'd1:if (pixels_tree1[386] <= 12) begin state_tree1<=2; end  else begin state_tree1<=123; end 
 
16'd2:if (pixels_tree1[714] <= 0) begin state_tree1<=3; end  else begin state_tree1<=66; end 
 
16'd3:if (pixels_tree1[346] <= 0) begin state_tree1<=4; end  else begin state_tree1<=35; end 
 
16'd4:if (pixels_tree1[350] <= 0) begin state_tree1<=5; end  else begin state_tree1<=20; end 
 
16'd5:if (pixels_tree1[156] <= 1) begin state_tree1<=6; end  else begin state_tree1<=13; end 
 
16'd6:if (pixels_tree1[430] <= 0) begin state_tree1<=7; end  else begin state_tree1<=10; end 
 
16'd7:if (pixels_tree1[176] <= 3) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd10:if (pixels_tree1[212] <= 2) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd13:if (pixels_tree1[319] <= 1) begin state_tree1<=14; end  else begin state_tree1<=17; end 
 
16'd14:if (pixels_tree1[490] <= 4) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd17:if (pixels_tree1[621] <= 9) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd20:if (pixels_tree1[548] <= 0) begin state_tree1<=21; end  else begin state_tree1<=28; end 
 
16'd21:if (pixels_tree1[579] <= 4) begin state_tree1<=22; end  else begin state_tree1<=25; end 
 
16'd22:if (pixels_tree1[273] <= 8) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd25:if (pixels_tree1[515] <= 81) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd28:if (pixels_tree1[553] <= 14) begin state_tree1<=29; end  else begin state_tree1<=32; end 
 
16'd29:if (pixels_tree1[153] <= 128) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd32:if (pixels_tree1[409] <= 3) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd35:if (pixels_tree1[464] <= 113) begin state_tree1<=36; end  else begin state_tree1<=51; end 
 
16'd36:if (pixels_tree1[465] <= 0) begin state_tree1<=37; end  else begin state_tree1<=44; end 
 
16'd37:if (pixels_tree1[490] <= 2) begin state_tree1<=38; end  else begin state_tree1<=41; end 
 
16'd38:if (pixels_tree1[353] <= 19) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd41:if (pixels_tree1[379] <= 1) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd44:if (pixels_tree1[352] <= 105) begin state_tree1<=45; end  else begin state_tree1<=48; end 
 
16'd45:if (pixels_tree1[485] <= 14) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd48:if (pixels_tree1[162] <= 2) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd51:if (pixels_tree1[710] <= 3) begin state_tree1<=52; end  else begin state_tree1<=59; end 
 
16'd52:if (pixels_tree1[354] <= 0) begin state_tree1<=53; end  else begin state_tree1<=56; end 
 
16'd53:if (pixels_tree1[219] <= 6) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd56:if (pixels_tree1[598] <= 50) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd59:if (pixels_tree1[430] <= 122) begin state_tree1<=60; end  else begin state_tree1<=63; end 
 
16'd60:if (pixels_tree1[352] <= 67) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd63:if (pixels_tree1[657] <= 133) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd66:if (pixels_tree1[460] <= 2) begin state_tree1<=67; end  else begin state_tree1<=96; end 
 
16'd67:if (pixels_tree1[378] <= 3) begin state_tree1<=68; end  else begin state_tree1<=83; end 
 
16'd68:if (pixels_tree1[485] <= 107) begin state_tree1<=69; end  else begin state_tree1<=76; end 
 
16'd69:if (pixels_tree1[483] <= 252) begin state_tree1<=70; end  else begin state_tree1<=73; end 
 
16'd70:if (pixels_tree1[351] <= 28) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd73:if (pixels_tree1[185] <= 72) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd76:if (pixels_tree1[293] <= 14) begin state_tree1<=77; end  else begin state_tree1<=80; end 
 
16'd77:if (pixels_tree1[464] <= 254) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd80:if (pixels_tree1[265] <= 227) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd83:if (pixels_tree1[524] <= 6) begin state_tree1<=84; end  else begin state_tree1<=91; end 
 
16'd84:if (pixels_tree1[408] <= 19) begin state_tree1<=85; end  else begin state_tree1<=88; end 
 
16'd85:if (pixels_tree1[180] <= 15) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd88:if (pixels_tree1[329] <= 35) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd91:if (pixels_tree1[260] <= 248) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=93; end 

16'd93:if (pixels_tree1[527] <= 22) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd96:if (pixels_tree1[298] <= 55) begin state_tree1<=97; end  else begin state_tree1<=110; end 
 
16'd97:if (pixels_tree1[188] <= 2) begin state_tree1<=98; end  else begin state_tree1<=105; end 
 
16'd98:if (pixels_tree1[401] <= 207) begin state_tree1<=99; end  else begin state_tree1<=102; end 
 
16'd99:if (pixels_tree1[378] <= 5) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd102:if (pixels_tree1[300] <= 144) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd105:if (pixels_tree1[383] <= 194) begin state_tree1<=106; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd106:if (pixels_tree1[301] <= 122) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd110:if (pixels_tree1[300] <= 7) begin state_tree1<=111; end  else begin state_tree1<=118; end 
 
16'd111:if (pixels_tree1[294] <= 137) begin state_tree1<=112; end  else begin state_tree1<=115; end 
 
16'd112:if (pixels_tree1[408] <= 165) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd115:if (pixels_tree1[439] <= 95) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd118:if (pixels_tree1[274] <= 137) begin state_tree1<=119; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd119:if (pixels_tree1[240] <= 1) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd123:if (pixels_tree1[625] <= 3) begin state_tree1<=124; end  else begin state_tree1<=179; end 
 
16'd124:if (pixels_tree1[462] <= 24) begin state_tree1<=125; end  else begin state_tree1<=156; end 
 
16'd125:if (pixels_tree1[597] <= 6) begin state_tree1<=126; end  else begin state_tree1<=141; end 
 
16'd126:if (pixels_tree1[512] <= 6) begin state_tree1<=127; end  else begin state_tree1<=134; end 
 
16'd127:if (pixels_tree1[295] <= 3) begin state_tree1<=128; end  else begin state_tree1<=131; end 
 
16'd128:if (pixels_tree1[212] <= 15) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd131:if (pixels_tree1[543] <= 52) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd134:if (pixels_tree1[633] <= 206) begin state_tree1<=135; end  else begin state_tree1<=138; end 
 
16'd135:if (pixels_tree1[383] <= 14) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd138:if (pixels_tree1[442] <= 40) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd141:if (pixels_tree1[271] <= 1) begin state_tree1<=142; end  else begin state_tree1<=149; end 
 
16'd142:if (pixels_tree1[215] <= 37) begin state_tree1<=143; end  else begin state_tree1<=146; end 
 
16'd143:if (pixels_tree1[437] <= 46) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd146:if (pixels_tree1[507] <= 85) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd149:if (pixels_tree1[488] <= 199) begin state_tree1<=150; end  else begin state_tree1<=153; end 
 
16'd150:if (pixels_tree1[375] <= 253) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd153:if (pixels_tree1[349] <= 126) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd156:if (pixels_tree1[566] <= 86) begin state_tree1<=157; end  else begin state_tree1<=172; end 
 
16'd157:if (pixels_tree1[542] <= 209) begin state_tree1<=158; end  else begin state_tree1<=165; end 
 
16'd158:if (pixels_tree1[572] <= 4) begin state_tree1<=159; end  else begin state_tree1<=162; end 
 
16'd159:if (pixels_tree1[372] <= 23) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd162:if (pixels_tree1[522] <= 76) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd165:if (pixels_tree1[435] <= 4) begin state_tree1<=166; end  else begin state_tree1<=169; end 
 
16'd166:if (pixels_tree1[427] <= 252) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd169:if (pixels_tree1[270] <= 32) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd172:if (pixels_tree1[440] <= 249) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=174; end 

16'd174:if (pixels_tree1[155] <= 77) begin state_tree1<=175; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd175:if (pixels_tree1[210] <= 125) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd179:if (pixels_tree1[460] <= 64) begin state_tree1<=180; end  else begin state_tree1<=211; end 
 
16'd180:if (pixels_tree1[455] <= 1) begin state_tree1<=181; end  else begin state_tree1<=196; end 
 
16'd181:if (pixels_tree1[492] <= 46) begin state_tree1<=182; end  else begin state_tree1<=189; end 
 
16'd182:if (pixels_tree1[352] <= 45) begin state_tree1<=183; end  else begin state_tree1<=186; end 
 
16'd183:if (pixels_tree1[557] <= 62) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd186:if (pixels_tree1[232] <= 188) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd189:if (pixels_tree1[569] <= 68) begin state_tree1<=190; end  else begin state_tree1<=193; end 
 
16'd190:if (pixels_tree1[566] <= 54) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd193:if (pixels_tree1[574] <= 35) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd196:if (pixels_tree1[350] <= 249) begin state_tree1<=197; end  else begin state_tree1<=204; end 
 
16'd197:if (pixels_tree1[490] <= 253) begin state_tree1<=198; end  else begin state_tree1<=201; end 
 
16'd198:if (pixels_tree1[119] <= 133) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd201:if (pixels_tree1[489] <= 253) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd204:if (pixels_tree1[272] <= 250) begin state_tree1<=205; end  else begin state_tree1<=208; end 
 
16'd205:if (pixels_tree1[187] <= 61) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd208:if (pixels_tree1[160] <= 243) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd211:if (pixels_tree1[320] <= 92) begin state_tree1<=212; end  else begin state_tree1<=227; end 
 
16'd212:if (pixels_tree1[239] <= 126) begin state_tree1<=213; end  else begin state_tree1<=220; end 
 
16'd213:if (pixels_tree1[316] <= 4) begin state_tree1<=214; end  else begin state_tree1<=217; end 
 
16'd214:if (pixels_tree1[262] <= 254) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd217:if (pixels_tree1[545] <= 214) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd220:if (pixels_tree1[409] <= 43) begin state_tree1<=221; end  else begin state_tree1<=224; end 
 
16'd221:if (pixels_tree1[655] <= 84) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd224:if (pixels_tree1[184] <= 251) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd227:if (pixels_tree1[435] <= 36) begin state_tree1<=228; end  else begin state_tree1<=233; end 
 
16'd228:if (pixels_tree1[175] <= 155) begin state_tree1<=229; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd229:if (pixels_tree1[402] <= 254) begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd233:if (pixels_tree1[521] <= 6) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end  else begin state_tree1<=235; end 

16'd235:if (pixels_tree1[274] <= 219) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd238:if (pixels_tree1[350] <= 155) begin state_tree1<=239; end  else begin state_tree1<=362; end 
 
16'd239:if (pixels_tree1[126] <= 0) begin state_tree1<=240; end  else begin state_tree1<=299; end 
 
16'd240:if (pixels_tree1[353] <= 2) begin state_tree1<=241; end  else begin state_tree1<=270; end 
 
16'd241:if (pixels_tree1[130] <= 8) begin state_tree1<=242; end  else begin state_tree1<=257; end 
 
16'd242:if (pixels_tree1[355] <= 2) begin state_tree1<=243; end  else begin state_tree1<=250; end 
 
16'd243:if (pixels_tree1[385] <= 4) begin state_tree1<=244; end  else begin state_tree1<=247; end 
 
16'd244:if (pixels_tree1[216] <= 1) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd247:if (pixels_tree1[209] <= 1) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd250:if (pixels_tree1[543] <= 12) begin state_tree1<=251; end  else begin state_tree1<=254; end 
 
16'd251:if (pixels_tree1[212] <= 31) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd254:if (pixels_tree1[554] <= 8) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd257:if (pixels_tree1[293] <= 18) begin state_tree1<=258; end  else begin state_tree1<=265; end 
 
16'd258:if (pixels_tree1[235] <= 1) begin state_tree1<=259; end  else begin state_tree1<=262; end 
 
16'd259:if (pixels_tree1[493] <= 20) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd262:if (pixels_tree1[101] <= 10) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd265:if (pixels_tree1[136] <= 38) begin state_tree1<=266; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd266:if (pixels_tree1[654] <= 97) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd270:if (pixels_tree1[212] <= 7) begin state_tree1<=271; end  else begin state_tree1<=284; end 
 
16'd271:if (pixels_tree1[95] <= 4) begin state_tree1<=272; end  else begin state_tree1<=279; end 
 
16'd272:if (pixels_tree1[401] <= 4) begin state_tree1<=273; end  else begin state_tree1<=276; end 
 
16'd273:if (pixels_tree1[266] <= 36) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd276:if (pixels_tree1[267] <= 48) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd279:if (pixels_tree1[237] <= 239) begin state_tree1<=280; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd280:if (pixels_tree1[295] <= 187) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd284:if (pixels_tree1[516] <= 85) begin state_tree1<=285; end  else begin state_tree1<=292; end 
 
16'd285:if (pixels_tree1[430] <= 0) begin state_tree1<=286; end  else begin state_tree1<=289; end 
 
16'd286:if (pixels_tree1[487] <= 71) begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd289:if (pixels_tree1[157] <= 1) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd292:if (pixels_tree1[433] <= 149) begin state_tree1<=293; end  else begin state_tree1<=296; end 
 
16'd293:if (pixels_tree1[655] <= 5) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd296:if (pixels_tree1[659] <= 1) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd299:if (pixels_tree1[243] <= 0) begin state_tree1<=300; end  else begin state_tree1<=331; end 
 
16'd300:if (pixels_tree1[401] <= 19) begin state_tree1<=301; end  else begin state_tree1<=316; end 
 
16'd301:if (pixels_tree1[323] <= 4) begin state_tree1<=302; end  else begin state_tree1<=309; end 
 
16'd302:if (pixels_tree1[150] <= 21) begin state_tree1<=303; end  else begin state_tree1<=306; end 
 
16'd303:if (pixels_tree1[213] <= 29) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd306:if (pixels_tree1[296] <= 21) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd309:if (pixels_tree1[513] <= 6) begin state_tree1<=310; end  else begin state_tree1<=313; end 
 
16'd310:if (pixels_tree1[516] <= 19) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd313:if (pixels_tree1[315] <= 215) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd316:if (pixels_tree1[148] <= 17) begin state_tree1<=317; end  else begin state_tree1<=324; end 
 
16'd317:if (pixels_tree1[544] <= 0) begin state_tree1<=318; end  else begin state_tree1<=321; end 
 
16'd318:if (pixels_tree1[627] <= 5) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd321:if (pixels_tree1[218] <= 18) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd324:if (pixels_tree1[549] <= 61) begin state_tree1<=325; end  else begin state_tree1<=328; end 
 
16'd325:if (pixels_tree1[320] <= 21) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd328:if (pixels_tree1[290] <= 7) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd331:if (pixels_tree1[546] <= 8) begin state_tree1<=332; end  else begin state_tree1<=347; end 
 
16'd332:if (pixels_tree1[298] <= 49) begin state_tree1<=333; end  else begin state_tree1<=340; end 
 
16'd333:if (pixels_tree1[327] <= 29) begin state_tree1<=334; end  else begin state_tree1<=337; end 
 
16'd334:if (pixels_tree1[181] <= 182) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd337:if (pixels_tree1[233] <= 6) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd340:if (pixels_tree1[376] <= 80) begin state_tree1<=341; end  else begin state_tree1<=344; end 
 
16'd341:if (pixels_tree1[488] <= 51) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd344:if (pixels_tree1[639] <= 31) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd347:if (pixels_tree1[350] <= 20) begin state_tree1<=348; end  else begin state_tree1<=355; end 
 
16'd348:if (pixels_tree1[155] <= 1) begin state_tree1<=349; end  else begin state_tree1<=352; end 
 
16'd349:if (pixels_tree1[186] <= 99) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd352:if (pixels_tree1[319] <= 70) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd355:if (pixels_tree1[347] <= 135) begin state_tree1<=356; end  else begin state_tree1<=359; end 
 
16'd356:if (pixels_tree1[554] <= 12) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd359:if (pixels_tree1[238] <= 218) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd362:if (pixels_tree1[207] <= 0) begin state_tree1<=363; end  else begin state_tree1<=424; end 
 
16'd363:if (pixels_tree1[462] <= 40) begin state_tree1<=364; end  else begin state_tree1<=393; end 
 
16'd364:if (pixels_tree1[123] <= 1) begin state_tree1<=365; end  else begin state_tree1<=380; end 
 
16'd365:if (pixels_tree1[191] <= 53) begin state_tree1<=366; end  else begin state_tree1<=373; end 
 
16'd366:if (pixels_tree1[152] <= 7) begin state_tree1<=367; end  else begin state_tree1<=370; end 
 
16'd367:if (pixels_tree1[514] <= 0) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd370:if (pixels_tree1[543] <= 48) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd373:if (pixels_tree1[432] <= 187) begin state_tree1<=374; end  else begin state_tree1<=377; end 
 
16'd374:if (pixels_tree1[542] <= 240) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd377:if (pixels_tree1[459] <= 186) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd380:if (pixels_tree1[512] <= 134) begin state_tree1<=381; end  else begin state_tree1<=388; end 
 
16'd381:if (pixels_tree1[458] <= 9) begin state_tree1<=382; end  else begin state_tree1<=385; end 
 
16'd382:if (pixels_tree1[612] <= 5) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd385:if (pixels_tree1[289] <= 34) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd388:if (pixels_tree1[433] <= 163) begin state_tree1<=389; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd389:if (pixels_tree1[301] <= 115) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd393:if (pixels_tree1[436] <= 208) begin state_tree1<=394; end  else begin state_tree1<=409; end 
 
16'd394:if (pixels_tree1[430] <= 3) begin state_tree1<=395; end  else begin state_tree1<=402; end 
 
16'd395:if (pixels_tree1[151] <= 201) begin state_tree1<=396; end  else begin state_tree1<=399; end 
 
16'd396:if (pixels_tree1[300] <= 66) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd399:if (pixels_tree1[149] <= 61) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd402:if (pixels_tree1[569] <= 248) begin state_tree1<=403; end  else begin state_tree1<=406; end 
 
16'd403:if (pixels_tree1[299] <= 4) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd406:if (pixels_tree1[467] <= 31) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd409:if (pixels_tree1[410] <= 0) begin state_tree1<=410; end  else begin state_tree1<=417; end 
 
16'd410:if (pixels_tree1[240] <= 67) begin state_tree1<=411; end  else begin state_tree1<=414; end 
 
16'd411:if (pixels_tree1[628] <= 132) begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd414:if (pixels_tree1[488] <= 11) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd417:if (pixels_tree1[710] <= 0) begin state_tree1<=418; end  else begin state_tree1<=421; end 
 
16'd418:if (pixels_tree1[570] <= 6) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd421:if (pixels_tree1[330] <= 78) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 7; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd424:if (pixels_tree1[515] <= 0) begin state_tree1<=425; end  else begin state_tree1<=456; end 
 
16'd425:if (pixels_tree1[316] <= 0) begin state_tree1<=426; end  else begin state_tree1<=441; end 
 
16'd426:if (pixels_tree1[654] <= 4) begin state_tree1<=427; end  else begin state_tree1<=434; end 
 
16'd427:if (pixels_tree1[491] <= 141) begin state_tree1<=428; end  else begin state_tree1<=431; end 
 
16'd428:if (pixels_tree1[525] <= 65) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd431:if (pixels_tree1[293] <= 176) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 1; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd434:if (pixels_tree1[319] <= 208) begin state_tree1<=435; end  else begin state_tree1<=438; end 
 
16'd435:if (pixels_tree1[513] <= 64) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd438:if (pixels_tree1[485] <= 73) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd441:if (pixels_tree1[607] <= 1) begin state_tree1<=442; end  else begin state_tree1<=449; end 
 
16'd442:if (pixels_tree1[624] <= 1) begin state_tree1<=443; end  else begin state_tree1<=446; end 
 
16'd443:if (pixels_tree1[240] <= 4) begin Label_tree_1<= 4; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd446:if (pixels_tree1[409] <= 9) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd449:if (pixels_tree1[326] <= 39) begin state_tree1<=450; end  else begin state_tree1<=453; end 
 
16'd450:if (pixels_tree1[490] <= 105) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd453:if (pixels_tree1[657] <= 5) begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd456:if (pixels_tree1[556] <= 1) begin state_tree1<=457; end  else begin state_tree1<=472; end 
 
16'd457:if (pixels_tree1[429] <= 155) begin state_tree1<=458; end  else begin state_tree1<=465; end 
 
16'd458:if (pixels_tree1[655] <= 0) begin state_tree1<=459; end  else begin state_tree1<=462; end 
 
16'd459:if (pixels_tree1[460] <= 2) begin Label_tree_1<= 3; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd462:if (pixels_tree1[292] <= 0) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd465:if (pixels_tree1[99] <= 0) begin state_tree1<=466; end  else begin state_tree1<=469; end 
 
16'd466:if (pixels_tree1[123] <= 92) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd469:if (pixels_tree1[568] <= 243) begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd472:if (pixels_tree1[385] <= 2) begin state_tree1<=473; end  else begin state_tree1<=478; end 
 
16'd473:if (pixels_tree1[708] <= 114) begin state_tree1<=474; end 
       else begin Label_tree_1<= 9; state_tree1<=0;ml_inference_completed_tree1<=1; end 
 
16'd474:if (pixels_tree1[439] <= 189) begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 2; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd478:if (pixels_tree1[95] <= 6) begin state_tree1<=479; end  else begin state_tree1<=482; end 
 
16'd479:if (pixels_tree1[456] <= 209) begin Label_tree_1<= 8; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 0; state_tree1<=0;ml_inference_completed_tree1<=1; end 

16'd482:if (pixels_tree1[500] <= 35) begin Label_tree_1<= 5; state_tree1<=0;ml_inference_completed_tree1<=1; end 
       else begin Label_tree_1<= 6; state_tree1<=0;ml_inference_completed_tree1<=1; end 

		 endcase
     
        end
    end




endmodule

module Binary_To_7Segment 
  (
   input       i_Clk,
	input [3:0] i_Binary_Num,
   output      o_Segment_A,
   output      o_Segment_B,
   output      o_Segment_C,
   output      o_Segment_D,
   output      o_Segment_E,
   output      o_Segment_F,
   output      o_Segment_G
   );
 
  reg [6:0]    r_Hex_Encoding = 7'h00;
   
  // Purpose: Creates a case statement for all possible input binary numbers.
  // Drives r_Hex_Encoding appropriately for each input combination.
  // Encoding at https://www.fpga4student.com/2017/09/seven-segment-led-display-controller-basys3-fpga.html
  always @(posedge i_Clk)
    begin
      case (i_Binary_Num)
        4'b0000 : r_Hex_Encoding <= 7'b0000001;
        4'b0001 : r_Hex_Encoding <= 7'b1001111;
        4'b0010 : r_Hex_Encoding <= 7'b0010010;
        4'b0011 : r_Hex_Encoding <= 7'b0000110;
        4'b0100 : r_Hex_Encoding <= 7'b1001100;         
        4'b0101 : r_Hex_Encoding <= 7'b0100100;
        4'b0110 : r_Hex_Encoding <= 7'b0100000;
        4'b0111 : r_Hex_Encoding <= 7'b0001111;
        4'b1000 : r_Hex_Encoding <= 7'b0000000;
        4'b1001 : r_Hex_Encoding <= 7'b0000100; 
		  4'b1010 : r_Hex_Encoding <= 7'b0001000; //a
		  4'b1011 : r_Hex_Encoding <= 7'b1100000; //b
		  4'b1100 : r_Hex_Encoding <= 7'b0110001;  //c
		  4'b1101 : r_Hex_Encoding <= 7'b1000010;  //d
		  4'b1110 : r_Hex_Encoding <= 7'b0110000;  //e
		  4'b1111 : r_Hex_Encoding <= 7'b0111000;  //f
        default: r_Hex_Encoding = 7'b1111111;
      endcase
    end // always @ (posedge i_Clk)
 
  // r_Hex_Encoding[7] is unused
  assign o_Segment_A = r_Hex_Encoding[6];
  assign o_Segment_B = r_Hex_Encoding[5];
  assign o_Segment_C = r_Hex_Encoding[4];
  assign o_Segment_D = r_Hex_Encoding[3];
  assign o_Segment_E = r_Hex_Encoding[2];
  assign o_Segment_F = r_Hex_Encoding[1];
  assign o_Segment_G = r_Hex_Encoding[0];
 
endmodule // Binary_To_7Segment



//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Receiver.  This receiver is able to
// receive 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When receive is complete o_rx_dv will be
// driven high for one clock cycle.
// https://www.nandland.com/vhdl/modules/module-uart-serial-port-rs232.html
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_rx   #(parameter CLKS_PER_BIT = 53)
  (
   input        i_Clock,
   input        i_Rx_Serial,
   output       o_Rx_DV,
   output [7:0] o_Rx_Byte
   );
    
  parameter s_IDLE         = 3'b000;
  parameter s_RX_START_BIT = 3'b001;
  parameter s_RX_DATA_BITS = 3'b010;
  parameter s_RX_STOP_BIT  = 3'b011; 
  parameter s_CLEANUP      = 3'b100;
   
  reg           r_Rx_Data_R = 1'b1;
  reg           r_Rx_Data   = 1'b1;
   
  reg [7:0]     r_Clock_Count = 0;
  reg [2:0]     r_Bit_Index   = 0; //8 bits total
  reg [7:0]     r_Rx_Byte     = 0;
  reg           r_Rx_DV       = 0;
  reg [2:0]     r_SM_Main     = 0;
   
  // Purpose: Double-register the incoming data.
  // This allows it to be used in the UART RX Clock Domain.
  // (It removes problems caused by metastability)
  always @(posedge i_Clock)
    begin
      r_Rx_Data_R <= i_Rx_Serial;
      r_Rx_Data   <= r_Rx_Data_R;
    end
   
   
  // Purpose: Control RX state machine
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            r_Rx_DV       <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (r_Rx_Data == 1'b0)          // Start bit detected
              r_SM_Main <= s_RX_START_BIT;
            else
              r_SM_Main <= s_IDLE;
          end
         
        // Check middle of start bit to make sure it's still low
        s_RX_START_BIT :
          begin
            if (r_Clock_Count == (CLKS_PER_BIT-1)/2)
              begin
                if (r_Rx_Data == 1'b0)
                  begin
                    r_Clock_Count <= 0;  // reset counter, found the middle
                    r_SM_Main     <= s_RX_DATA_BITS;
                  end
                else
                  r_SM_Main <= s_IDLE;
              end
            else
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_START_BIT;
              end
          end // case: s_RX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles to sample serial data
        s_RX_DATA_BITS :
          begin
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count          <= 0;
                r_Rx_Byte[r_Bit_Index] <= r_Rx_Data;
                 
                // Check if we have received all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_RX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_RX_STOP_BIT;
                  end
              end
          end // case: s_RX_DATA_BITS
     
     
        // Receive Stop bit.  Stop bit = 1
        s_RX_STOP_BIT :
          begin
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_RX_STOP_BIT;
              end
            else
              begin
                r_Rx_DV       <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
              end
          end // case: s_RX_STOP_BIT
     
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_SM_Main <= s_IDLE;
            r_Rx_DV   <= 1'b0;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end   
   
  assign o_Rx_DV   = r_Rx_DV;
  assign o_Rx_Byte = r_Rx_Byte;
   
endmodule // uart_rx


//////////////////////////////////////////////////////////////////////
// File Downloaded from http://www.nandland.com
//////////////////////////////////////////////////////////////////////
// This file contains the UART Transmitter.  This transmitter is able
// to transmit 8 bits of serial data, one start bit, one stop bit,
// and no parity bit.  When transmit is complete o_Tx_done will be
// driven high for one clock cycle.
//
// Set Parameter CLKS_PER_BIT as follows:
// CLKS_PER_BIT = (Frequency of i_Clock)/(Frequency of UART)
// Example: 50 MHz Clock, 921600 baud UART
// (50000000)/(921600) = 53
  
module uart_tx 
  #(parameter CLKS_PER_BIT = 53)
  (
   input       i_Clock,
   input       i_Tx_DV,
   input [7:0] i_Tx_Byte, 
   output      o_Tx_Active,
   output reg  o_Tx_Serial,
   output      o_Tx_Done
   );
  
  parameter s_IDLE         = 3'b000;
  parameter s_TX_START_BIT = 3'b001;
  parameter s_TX_DATA_BITS = 3'b010;
  parameter s_TX_STOP_BIT  = 3'b011;
  parameter s_CLEANUP      = 3'b100;
   
  reg [2:0]    r_SM_Main     = 0;
  reg [7:0]    r_Clock_Count = 0;
  reg [2:0]    r_Bit_Index   = 0;
  reg [7:0]    r_Tx_Data     = 0;
  reg          r_Tx_Done     = 0;
  reg          r_Tx_Active   = 0;
     
  always @(posedge i_Clock)
    begin
       
      case (r_SM_Main)
        s_IDLE :
          begin
            o_Tx_Serial   <= 1'b1;         // Drive Line High for Idle
            r_Tx_Done     <= 1'b0;
            r_Clock_Count <= 0;
            r_Bit_Index   <= 0;
             
            if (i_Tx_DV == 1'b1)
              begin
                r_Tx_Active <= 1'b1;
                r_Tx_Data   <= i_Tx_Byte;
                r_SM_Main   <= s_TX_START_BIT;
              end
            else
              r_SM_Main <= s_IDLE;
          end // case: s_IDLE
         
         
        // Send out Start Bit. Start bit = 0
        s_TX_START_BIT :
          begin
            o_Tx_Serial <= 1'b0;
             
            // Wait CLKS_PER_BIT-1 clock cycles for start bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_START_BIT;
              end
            else
              begin
                r_Clock_Count <= 0;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
          end // case: s_TX_START_BIT
         
         
        // Wait CLKS_PER_BIT-1 clock cycles for data bits to finish         
        s_TX_DATA_BITS :
          begin
            o_Tx_Serial <= r_Tx_Data[r_Bit_Index];
             
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_DATA_BITS;
              end
            else
              begin
                r_Clock_Count <= 0;
                 
                // Check if we have sent out all bits
                if (r_Bit_Index < 7)
                  begin
                    r_Bit_Index <= r_Bit_Index + 1;
                    r_SM_Main   <= s_TX_DATA_BITS;
                  end
                else
                  begin
                    r_Bit_Index <= 0;
                    r_SM_Main   <= s_TX_STOP_BIT;
                  end
              end
          end // case: s_TX_DATA_BITS
         
         
        // Send out Stop bit.  Stop bit = 1
        s_TX_STOP_BIT :
          begin
            o_Tx_Serial <= 1'b1;
             
            // Wait CLKS_PER_BIT-1 clock cycles for Stop bit to finish
            if (r_Clock_Count < CLKS_PER_BIT-1)
              begin
                r_Clock_Count <= r_Clock_Count + 1;
                r_SM_Main     <= s_TX_STOP_BIT;
              end
            else
              begin
                r_Tx_Done     <= 1'b1;
                r_Clock_Count <= 0;
                r_SM_Main     <= s_CLEANUP;
                r_Tx_Active   <= 1'b0;
              end
          end // case: s_Tx_STOP_BIT
         
         
        // Stay here 1 clock
        s_CLEANUP :
          begin
            r_Tx_Done <= 1'b1;
            r_SM_Main <= s_IDLE;
          end
         
         
        default :
          r_SM_Main <= s_IDLE;
         
      endcase
    end
 
  assign o_Tx_Active = r_Tx_Active;
  assign o_Tx_Done   = r_Tx_Done;
   
endmodule

